version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../certs:/etc/nginx/certs:ro
    ports:
      - "3000:3000"   # Gitea HTTPS
      - "3001:3001"   # Grafana HTTPS
      - "8080:8080"   # Infisical HTTPS
      - "9090:9090"   # Prometheus HTTPS
      - "9093:9093"   # Alertmanager HTTPS
    depends_on:
      - gitea
      - infisical
      - prometheus
      - grafana
      - alertmanager
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__DOMAIN=lenny
      - GITEA__server__ROOT_URL=https://lenny:3000/
      - GITEA__server__PROTOCOL=https
    volumes:
      - ../gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3000"
    ports:
      - "2222:22"  # SSH still exposed directly
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  infisical-db:
    image: postgres:16-alpine
    container_name: infisical-db
    environment:
      - POSTGRES_USER=infisical
      - POSTGRES_PASSWORD=infisical
      - POSTGRES_DB=infisical
    volumes:
      - infisical-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  infisical-redis:
    image: redis:7-alpine
    container_name: infisical-redis
    volumes:
      - infisical-redis-data:/data
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  infisical:
    image: infisical/infisical:latest
    container_name: infisical
    environment:
      - DB_CONNECTION_URI=postgres://infisical:infisical@infisical-db:5432/infisical
      - REDIS_URL=redis://infisical-redis:6379
      - ENCRYPTION_KEY=CHANGE_ME_32_CHAR_HEX  # Generate with: openssl rand -hex 32
      - AUTH_SECRET=CHANGE_ME_32_CHAR_HEX     # Generate with: openssl rand -hex 32
      - SITE_URL=https://lenny:8080
    depends_on:
      - infisical-db
      - infisical-redis
    expose:
      - "8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "nobody"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
    expose:
      - "9090"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://lenny:3001
    expose:
      - "3000"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    expose:
      - "9093"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  prometheus-data:
  grafana-data:
  infisical-db-data:
  infisical-redis-data:
